### ISSUE TITLE
Chrome and Tomcat

### ISSUE THREAD

**Issue by IOhacker** [collab-project/videojs-record#517]
## Description
We have recorded the video in webm format but when sending the file using POST to API Rest using Chrome we always have Multipart Errors, in Firefox it is working.

```
org.springframework.web.multipart.MultipartException: Failed to parse multipart servlet request; nested exception is org.apache.commons.fileupload.FileUploadException: Stream closed,
	at org.springframework.web.multipart.commons.CommonsMultipartResolver.parseRequest(CommonsMultipartResolver.java:169),
	at org.springframework.web.multipart.commons.CommonsMultipartResolver.resolveMultipart(CommonsMultipartResolver.java:143),
	at org.springframework.web.servlet.DispatcherServlet.checkMultipart(DispatcherServlet.java:1177),
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1012),
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943),
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006),
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909),
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652),
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883),
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733),
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231),
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166),
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52),
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193),
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166),
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:713),
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:462),
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:387),
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:315),
	at org.springframework.boot.web.servlet.support.ErrorPageFilter.handleErrorStatus(ErrorPageFilter.java:160),
	at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:130),
	at org.springframework.boot.web.servlet.support.ErrorPageFilter.access$000(ErrorPageFilter.java:66),
	at org.springframework.boot.web.servlet.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:103),
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119),
	at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:121),
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193),
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166),
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:114),
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:104),
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119),
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193),
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166),
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201),
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119),
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193),
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166),
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199),
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97),
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:544),
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143),
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81),
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690),
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78),
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343),
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:616),
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65),
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818),
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1626),
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49),
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128),
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628),
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61),
	at java.base/java.lang.Thread.run(Thread.java:836),
Caused by: org.apache.commons.fileupload.FileUploadException: Stream closed,
	at org.apache.commons.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:361),
	at org.apache.commons.fileupload.servlet.ServletFileUpload.parseRequest(ServletFileUpload.java:113),
	at org.springframework.web.multipart.commons.CommonsMultipartResolver.parseRequest(CommonsMultipartResolver.java:159),
	... 52 common frames omitted,
Caused by: java.io.IOException: Stream closed,
	at org.apache.catalina.connector.InputBuffer.read(InputBuffer.java:367),
	at org.apache.catalina.connector.CoyoteInputStream.read(CoyoteInputStream.java:183),
	at org.apache.commons.fileupload.MultipartStream$ItemInputStream.makeAvailable(MultipartStream.java:1027),
	at org.apache.commons.fileupload.MultipartStream$ItemInputStream.read(MultipartStream.java:931),
	at java.base/java.io.InputStream.read(InputStream.java:205),
	at org.apache.commons.fileupload.util.Streams.copy(Streams.java:98),
	at org.apache.commons.fileupload.util.Streams.copy(Streams.java:68),
	at org.apache.commons.fileupload.MultipartStream.readBodyData(MultipartStream.java:622),
	at org.apache.commons.fileupload.MultipartStream.discardBodyData(MultipartStream.java:646),
	at org.apache.commons.fileupload.MultipartStream.skipPreamble(MultipartStream.java:664),
	at org.apache.commons.fileupload.FileUploadBase$FileItemIteratorImpl.findNextItem(FileUploadBase.java:1037),
	at org.apache.commons.fileupload.FileUploadBase$FileItemIteratorImpl.<init>(FileUploadBase.java:1017),
	at org.apache.commons.fileupload.FileUploadBase.getItemIterator(FileUploadBase.java:309),
	at org.apache.commons.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:333),
	... 54 common frames omitted,
```

## Results
```
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: es-419,es;q=0.9
Connection: keep-alive
Content-Length: 761927
Content-Type: multipart/form-data; boundary=----WebKitFormBoundarycf9arXUuxmcBCHDx
Host: myhost.com
Origin: http://localhost:4200
Referer: http://localhost:4200/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 
-----------------chrome
```

### Expected
```
Accept 	application/json, text/plain, */*
Accept-Encoding 	gzip, deflate, br
Accept-Language 	es-MX,es;q=0.8,en-US;q=0.5,en;q=0.3
Connection 	keep-alive
Content-Length 	883840
Content-Type 	multipart/form-data; boundary=---------------------------42681271376610151333440022124
Host 	myhost.com
Origin 	http://localhost:4200
Referer 	http://localhost:4200/video
User-Agent 	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:81.0) Gecko/20100101 Firefox/81.0
X-Gravitee-Api-Key
```
-------------------firefox--------------------

**Comment by thijstriemstra** [comment]
@IOhacker can you reproduce it with an example like https://github.com/collab-project/videojs-record/blob/master/examples/upload/simple.html?

**Comment by IOhacker** [comment]
Hi,

I have replaced the way it is uploaded (using Angular 8).

    const formData: FormData = new FormData();
    let ext=(file.name).split(".");
    formData.append('name', name);
    formData.append('file', file);
    let url = environment.apis_url + '/V1.0/upload' + urlComplement;  
    return this.http.post(url, formData, { headers: httpHeaders }).pipe(
      retry(3),
      catchError(error => {
        console.log(error);
        return EMPTY;
      }),
      shareReplay()
    );

**Comment by thijstriemstra** [comment]
@IOhacker ok, and it works now?

**Comment by thijstriemstra** [comment]
No feedback, closing.
