### ISSUE TITLE
Cannot read property 'startsWith' of undefined (removeRecording())

### ISSUE THREAD

**Issue by karlerss** [collab-project/videojs-record#575]
## Description
Caught this in production.

## Steps to reproduce
1. start recording

### Expected
Starts recording

### Actual
Screen black.

### Error output
```
TypeError: Cannot read property 'startsWith' of undefined
  at Record.removeRecording(webpack://VideojsRecord/./src/js/videojs.record.js?:1072:54)
  at Record.startVideoPreview(webpack://VideojsRecord/./src/js/videojs.record.js?:1184:12)
  at Record.start(webpack://VideojsRecord/./src/js/videojs.record.js?:673:18)
  at click(/js/video/public.js:2:1624734)
  at He(/js/video/public.js:2:1643915)
  at HTMLButtonElement.n(/js/video/public.js:2:1645660)
  at HTMLButtonElement.Qr.o._wrapper(/js/video/public.js:2:1680935)
  at HTMLButtonElement.r(/js/video/public.js:2:1517762)
```

#### videojs
4.1.1
#### browsers
Chrome 90.0.4430
#### OSes
Windows 10

**Comment by thijstriemstra** [comment]
can you show some code that reproduces this issue?

**Comment by karlerss** [comment]
````
options: {
                    controls: false,
                    autoplay: false,
                    fluid: true,
                    loop: false,
                    bigPlayButton: false,
                    plugins: {
                        record: {
                            audio: true,
                            debug: true,
                            maxLength: 10 * 60,
                            video: {
                                // video media constraints: set resolution of camera
                                width: 640,
                                height: 480
                            },
                        }
                    }
                }
```

```
                this.player = videojs(`recorder-${this._uid}`, this.options, () => {
                    if (this.player) {
                        this.player.record().getDevice();
                    }
                });
```

Error happens when calling:
```
this.player.record().start();
```

For context - the implementation works in production, and has worked fine for thousands of users. I caught this with Sentry (twice) and was messaged by a user.

**Comment by thijstriemstra** [comment]
> My suggestion, add check if this.mediaElement.src is defined.

Agreed. Opened #576

**Comment by karlerss** [comment]
Thank you very much! This software has been really useful.
